<?php

namespace MyFantasyPlaceBundle\Repository;

/**
 * DartsPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DartsPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
