<?php

namespace MyFantasyPlaceBundle\Repository;

/**
 * SnookerPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnookerPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
