<?php

namespace MyFantasyPlaceBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use MyFantasyPlaceBundle\Entity\UserSnookerPlayer;

/**
 * UserSnookerPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSnookerPlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(UserSnookerPlayer::class));
    }

    public function insert($transfer)
    {
        $this->_em->persist($transfer);
        $this->_em->flush();

        return true;
    }
}
