<?php

namespace MyFantasyPlaceBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use MyFantasyPlaceBundle\Entity\UserDartsPlayer;
use Doctrine\ORM\Mapping;

/**
 * UserDartsPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDartsPlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(UserDartsPlayer::class));
    }

    public function insert($transfer)
    {
        $this->_em->persist($transfer);
        $this->_em->flush();

        return true;
    }
}
